server:
  port: 8081

spring:
  profiles:
    active: "postgresql"
  data:
    mongodb:
      database: logging
      host:  ${{ secrets.AWS_DB  }}
      username: root
      password: password
      port: 27017
      authentication-database: admin
  redis:
    url: ${{ secrets.AWS_DB  }}
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  rabbitmq:
    host: ${{ secrets.AWS_DB  }}
    username: guest
    password: guest
    port: 5672

---
spring:
  profiles: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_advanced
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  profiles: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${{ secrets.AWS_DB  }}:5432/ajmc
    username: postgres
    password: SevenEightTwo782
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
